options:
  deploymentTarget:
    macOS: "10.11"
  settingPresets: none
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 3
  tabWidth: 3

attributes:
   ORGANIZATIONNAME: WaveLabs
   LastUpgradeCheck: "1000"
   
configFiles:
   Debug: Configuration/Project.xcconfig
   Release: Configuration/Project.xcconfig

name: Attenuator

targets:
       
  AUHost:
    type: application
    platform: macOS
    settings:
      INFOPLIST_FILE: SampleAUHost/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: ua.com.wavelabs.AUHost
      CODE_SIGN_ENTITLEMENTS: SampleAUHost/App.entitlements
      CODE_SIGN_IDENTITY: Mac Developer
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: E27KE6VTF6
      DEPLOYMENT_LOCATION: YES
    configFiles:
       Debug: Vendor/WL/Shared/Configuration/App-macOS.xcconfig
       Release: Vendor/WL/Shared/Configuration/App-macOS.xcconfig
    prebuildScripts:
       - script: '[[ -r ~/.bashrc ]] && . ~/.bashrc && ruby -r "`pwd`/Automation.rb" -e "Automation.verifyHost"'
         name: "Run Script: Verify"
         shell: /bin/bash
    sources:
       - SampleAUHost
       - Shared
       - Vendor/WL/Core
       - Vendor/WL/Foundation
       - Vendor/WL/Media
       - Vendor/WL/Types
       - Vendor/WL/AppKit
       
  Attenuator:
    type: application
    platform: macOS
    settings:
      INFOPLIST_FILE: SampleAUPlugin/Attenuator/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: ua.com.wavelabs.Attenuator
      CODE_SIGN_ENTITLEMENTS: SampleAUPlugin/Attenuator/App.entitlements
      CODE_SIGN_IDENTITY: Mac Developer
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: E27KE6VTF6
      DEPLOYMENT_LOCATION: YES
    configFiles:
       Debug: Vendor/WL/Shared/Configuration/App-macOS.xcconfig
       Release: Vendor/WL/Shared/Configuration/App-macOS.xcconfig
    postbuildScripts:
       - script: '[[ -r ~/.bashrc ]] && . ~/.bashrc && ruby -r "`pwd`/Automation.rb" -e "Automation.post"'
         name: "Run Script: Post-Build"
         shell: /bin/bash
    sources:
       - SampleAUPlugin/Attenuator
       - SampleAUPlugin/AttenuatorKit
       - Shared
       - Vendor/WL/Core
       - Vendor/WL/Foundation
       - Vendor/WL/Media
       - Vendor/WL/Types
       - Vendor/WL/AppKit
    dependencies:
       - target: AttenuatorAU

  AttenuatorAU:
    type: app-extension
    platform: macOS
    settings:
      INFOPLIST_FILE: SampleAUPlugin/AttenuatorAU/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: ua.com.wavelabs.Attenuator.AttenuatorAU
      CODE_SIGN_ENTITLEMENTS: SampleAUPlugin/AttenuatorAU/App.entitlements
      CODE_SIGN_IDENTITY: Mac Developer
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: E27KE6VTF6
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    configFiles:
       Debug: Vendor/WL/Shared/Configuration/Framework-macOS.xcconfig
       Release: Vendor/WL/Shared/Configuration/Framework-macOS.xcconfig
    sources:
       - SampleAUPlugin/AttenuatorKit
       - Vendor/WL/Core
       - Vendor/WL/Foundation
       - Vendor/WL/Media
       - Vendor/WL/Types
       - Vendor/WL/AppKit
       
schemes:
       
   AUHost:
     build:
       targets:
         AUHost: [run, archive]
         
   Attenuator:
     build:
       targets:
         Attenuator: [run, archive]

