include:
  - Vendor/mc/mcxUIReusable/project.yml
  - Vendor/mc/mcxAppKitMedia/project.yml
  - Vendor/mc/mcxFoundation/project.yml
  - Vendor/mc/mcxMediaAU/project.yml
  - Vendor/mc/mcxMedia/project.yml
  - Vendor/mc/mcxMediaExtensions/project.yml
  - Vendor/mc/mcxGraphicsExtensions/project.yml
name: Shared
settings:
  AWL_LIB_SRC: Vendor/mc
  MACOSX_DEPLOYMENT_TARGET: 10.12
aggregateTargets:
  Shared:
    targets:
      - mcxUIReusable
      - mcxAppKitMedia
      - mcxFoundation
      - mcxMediaAU
      - mcxMedia
      - mcxMediaExtensions
      - mcxGraphicsExtensions
