# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

libraryFilePath = "#{ENV['AWL_LIB_SRC']}/Scripts/WL.rb"
if File.exists?(libraryFilePath)
   import libraryFilePath
else
   import "#{ENV['PWD']}/Vendor/WL/Scripts/WL.rb"
end

XCodeProjectFilePath = "#{ENV['PWD']}/Attenuator.xcodeproj"
XCodeProjectSchema = "Attenuator"

desc "Builds project."
lane :build do
   XcodeBuilder.new(XCodeProjectFilePath).build(XCodeProjectSchema)
end

desc "Cleans project."
lane :clean do
   XcodeBuilder.new(XCodeProjectFilePath).clean(XCodeProjectSchema)
end

desc "Builds when under CI (i.e. Travis)."
lane :ci do
   XcodeBuilder.new(XCodeProjectFilePath).ci(XCodeProjectSchema)
end

desc "Archives project."
lane :archive do
   XcodeBuilder.new(XCodeProjectFilePath).archive(XCodeProjectSchema)
end
